### ISSUE TITLE
SSH Kernelの利用について

### ISSUE THREAD

**Issue by Sa2shi** [NII-cloud-operation/Jupyter-LC_docker#112]
お世話になっております。

現在Jupyter-LC_dockerではBash/Python 3がサポートされていますが、SSHkernelも利用したいと考えています。
https://github.com/NII-cloud-operation/sshkernel/tree/master
→2点、ご相談です。

【Q.1】この場合、[こちら](https://github.com/NII-cloud-operation/Jupyter-LC_docker/tree/master?tab=readme-ov-file#basic-use)にあるように、

> niicloudoperation/notebook

を直接docker runで実行するのでなく、一度ローカルにgit cloneで引っ張ってきてから、

https://github.com/NII-cloud-operation/Jupyter-LC_docker/blob/e22ea2e31815db7d46e73b0ef92f73056a367e0a/Dockerfile#L100-L105
あたりに、SSH Kernelの利用に関して追記し、イメージをビルド＆利用すればよいでしょうか。

【Q.2】Jupyter-LC_dockerでのSSH Kernelサポートのご予定はありますでしょうか。

お手数ですが、ご教示いただけますと幸いです。

**Comment by yacchin1205** [comment]
ありがとうございます。以下、回答させていただきます。

Q.1:
> SSH Kernelの利用に関して追記し、イメージをビルド＆利用すればよいでしょうか。

はい、その方針でOKだと思います。試してみてください。

Q.2:
> Jupyter-LC_dockerでのSSH Kernelサポートのご予定はありますでしょうか。

予定はありません。対外発表等では説明させていただいておりますが、Notebookから管理対象システムへの操作に関しては、Ansible等の構成管理ツールに基づいて実施する形をとっています。どうぞよろしくお願いいたします。
