### ISSUE TITLE
getpass.getpass() not working

### ISSUE THREAD

**Issue by nasuno-ascade** [NII-cloud-operation/Jupyter-LC_docker#79]
[niicloudoperation/notebook:latest](https://hub.docker.com/r/niicloudoperation/notebook) のDockerイメージで getpass.getpass() の入力欄が出てこない状態になります。
NII-cloud-operation/Jupyter-LC_docker を手元で改めて docker build してみましたが状況は変わりませんでした。

```
import getpass
a = getpass.getpass()
```

一方、ベースとなっている [jupyter/scipy-notebook:latest](https://hub.docker.com/r/jupyter/scipy-notebook) (Digest:sha256:dae4d5c5f05) のほうは問題ありませんでした。

**Comment by yacchin1205** [comment]
ご報告ありがとうございます。Jupyter-LC_wrapperの問題でした https://github.com/NII-cloud-operation/Jupyter-LC_wrapper/pull/66 。今は修正したものが niicloudoperation/notebook:latest https://hub.docker.com/repository/docker/niicloudoperation/notebook に入っているのでそちらをお試しください！
